-- 이미지 처리 작업 테이블. 우리 서버가 작업 상태의 source of truth로 보관한다.
-- 멱등성은 idempotency_key 유니크 제약으로 보장하고(요구 4.1), 상태/식별자/결과를 추적한다.
CREATE TABLE jobs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_id     UUID         NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    image_url       VARCHAR(2048) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    worker_job_id   VARCHAR(255),
    result          TEXT,
    error_code      VARCHAR(30),
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    claimed_until   TIMESTAMP WITH TIME ZONE,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 클라이언트 노출 식별자(trackingId)와 멱등 키는 각각 유일해야 한다.
-- 멱등 키 유니크 제약이 동시 중복 요청을 DB 레벨에서 하나로 수렴시키는 핵심 장치다.
ALTER TABLE jobs ADD CONSTRAINT uq_jobs_tracking_id UNIQUE (tracking_id);
ALTER TABLE jobs ADD CONSTRAINT uq_jobs_idempotency_key UNIQUE (idempotency_key);

-- 스케줄러는 (상태, 다음 픽업 시각)으로 claim 대상을 찾는다. 해당 픽업 쿼리를 위한 복합 인덱스.
CREATE INDEX idx_jobs_claim ON jobs (status, next_attempt_at);
